name: Build and deploy ASP.Net Core app to Azure Web App - clipchampaiwebclientpoc

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Print current directory
        run: |
          echo "Current directory:"
          pwd
          echo "Listing contents:"
          dir

      - name: Dotnet publish
        run: dotnet publish --configuration Release --output D:\a\dotnetcore-docs-hello-world\dotnetcore-docs-hello-world\myapp

      - name: Print contents of publish directory
        run: |
          echo "Listing contents of D:\\a\\dotnetcore-docs-hello-world\\dotnetcore-docs-hello-world\\myapp:"
          dir D:\a\dotnetcore-docs-hello-world\dotnetcore-docs-hello-world\myapp || echo "Directory D:\\a\\dotnetcore-docs-hello-world\\dotnetcore-docs-hello-world\\myapp does not exist."

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: D:\a\dotnetcore-docs-hello-world\dotnetcore-docs-hello-world\myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app

      - name: Print contents of artifact directory
        run: |
          echo "Listing contents of artifact directory:"
          dir . || echo "Directory does not exist."

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E4F9FB7B7C6542AFBC9CBD0D90163919 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_53DFFC2547D849C4937D1CD93E98E06E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F2BADA6F9BB3404C9B43A03CCB0216DD }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'clipchampaiwebclientpoc'
          slot-name: 'Production'
          package: D:\a\dotnetcore-docs-hello-world\dotnetcore-docs-hello-world\myapp
